server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          __path__: /logs/system/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            logger: logger
            category: category
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          logger:
          category:

  - job_name: data
    static_configs:
      - targets:
          - localhost
        labels:
          job: data
          __path__: /logs/data/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            logger: logger
            category: category
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          logger:
          category:

  - job_name: model
    static_configs:
      - targets:
          - localhost
        labels:
          job: model
          __path__: /logs/model/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            logger: logger
            category: category
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          logger:
          category:

  - job_name: trade
    static_configs:
      - targets:
          - localhost
        labels:
          job: trade
          __path__: /logs/trade/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            logger: logger
            category: category
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          logger:
          category:

  - job_name: error
    static_configs:
      - targets:
          - localhost
        labels:
          job: error
          __path__: /logs/error/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            logger: logger
            category: category
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          logger:
          category:

  - job_name: security
    static_configs:
      - targets:
          - localhost
        labels:
          job: security
          __path__: /logs/security/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            logger: logger
            category: category
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          logger:
          category:
