global:
  resolve_timeout: 5m
  smtp_from: 'alerts@example.com'
  smtp_smarthost: 'smtp.example.com:587'
  smtp_auth_username: 'alerts@example.com'
  smtp_auth_password: 'password'
  smtp_require_tls: true

route:
  group_by: ['alertname', 'type']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'email-alerts'
  routes:
    - match:
        severity: critical
      receiver: 'slack-critical'
      continue: true
    - match:
        severity: critical
      receiver: 'email-alerts'
      continue: true
    - match:
        severity: warning
      receiver: 'slack-warnings'
      continue: true
    - match:
        type: system
      receiver: 'system-team'
    - match:
        type: api
      receiver: 'api-team'
    - match:
        type: model
      receiver: 'model-team'
    - match:
        type: trade
      receiver: 'trade-team'

receivers:
  - name: 'email-alerts'
    email_configs:
      - to: 'admin@example.com'
        send_resolved: true
        html: |
          {{ range .Alerts }}
          <h3>{{ .Annotations.summary }}</h3>
          <p><strong>描述:</strong> {{ .Annotations.description }}</p>
          <p><strong>嚴重性:</strong> {{ .Labels.severity }}</p>
          <p><strong>類型:</strong> {{ .Labels.type }}</p>
          <p><strong>開始時間:</strong> {{ .StartsAt }}</p>
          {{ if .EndsAt }}
          <p><strong>結束時間:</strong> {{ .EndsAt }}</p>
          {{ end }}
          {{ end }}

  - name: 'slack-critical'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/XXXXXXXXX/XXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXX'
        channel: '#alerts-critical'
        send_resolved: true
        title: '{{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *{{ .Annotations.summary }}*
          {{ .Annotations.description }}
          *嚴重性:* {{ .Labels.severity }}
          *類型:* {{ .Labels.type }}
          *開始時間:* {{ .StartsAt }}
          {{ if .EndsAt }}
          *結束時間:* {{ .EndsAt }}
          {{ end }}
          {{ end }}

  - name: 'slack-warnings'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/XXXXXXXXX/XXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXX'
        channel: '#alerts-warnings'
        send_resolved: true
        title: '{{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *{{ .Annotations.summary }}*
          {{ .Annotations.description }}
          *嚴重性:* {{ .Labels.severity }}
          *類型:* {{ .Labels.type }}
          *開始時間:* {{ .StartsAt }}
          {{ if .EndsAt }}
          *結束時間:* {{ .EndsAt }}
          {{ end }}
          {{ end }}

  - name: 'system-team'
    email_configs:
      - to: 'system-team@example.com'
        send_resolved: true

  - name: 'api-team'
    email_configs:
      - to: 'api-team@example.com'
        send_resolved: true

  - name: 'model-team'
    email_configs:
      - to: 'model-team@example.com'
        send_resolved: true

  - name: 'trade-team'
    email_configs:
      - to: 'trade-team@example.com'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'type']
