apiVersion: v1
kind: Secret
metadata:
  name: ai-trading-secrets
  namespace: ai-trading
  labels:
    app: ai-trading-system
    component: secrets
type: Opaque
data:
  # 注意：這些是 base64 編碼的範例值，實際部署時需要替換為真實值
  # 使用 echo -n "your_password" | base64 來生成 base64 編碼
  
  # 資料庫密碼 (範例: "secure_password")
  POSTGRES_PASSWORD: c2VjdXJlX3Bhc3N3b3Jk
  
  # Redis 密碼 (範例: "redis_password")
  REDIS_PASSWORD: cmVkaXNfcGFzc3dvcmQ=
  
  # JWT 密鑰 (範例: "jwt_secret_key_change_in_production")
  JWT_SECRET_KEY: and0X3NlY3JldF9rZXlfY2hhbmdlX2luX3Byb2R1Y3Rpb24=
  
  # Grafana 管理員密碼 (範例: "grafana_admin_password")
  GRAFANA_PASSWORD: Z3JhZmFuYV9hZG1pbl9wYXNzd29yZA==
  
  # 加密金鑰 (範例: "encryption_key_32_chars_long_123")
  ENCRYPTION_KEY: ZW5jcnlwdGlvbl9rZXlfMzJfY2hhcnNfbG9uZ18xMjM=
  
  # Fernet 金鑰 (範例: "fernet_key_32_chars_long_1234567")
  FERNET_KEY: ZmVybmV0X2tleV8zMl9jaGFyc19sb25nXzEyMzQ1Njc=
  
  # Session 密鑰 (範例: "session_secret_key_change_me")
  SESSION_SECRET_KEY: c2Vzc2lvbl9zZWNyZXRfa2V5X2NoYW5nZV9tZQ==

---
apiVersion: v1
kind: Secret
metadata:
  name: ai-trading-api-keys
  namespace: ai-trading
  labels:
    app: ai-trading-system
    component: api-keys
type: Opaque
data:
  # 外部 API 金鑰 (範例值，實際使用時需要替換)
  
  # 股票資料 API 金鑰
  TWSE_API_KEY: dHdzZV9hcGlfa2V5X2hlcmU=
  TPEX_API_KEY: dHBleF9hcGlfa2V5X2hlcmU=
  YAHOO_FINANCE_API_KEY: eWFob29fZmluYW5jZV9hcGlfa2V5X2hlcmU=
  ALPHA_VANTAGE_API_KEY: YWxwaGFfdmFudGFnZV9hcGlfa2V5X2hlcmU=
  FINNHUB_API_KEY: Zmlubmh1Yl9hcGlfa2V5X2hlcmU=
  
  # AI 服務 API 金鑰
  OPENAI_API_KEY: b3BlbmFpX2FwaV9rZXlfaGVyZQ==
  HUGGINGFACE_API_KEY: aHVnZ2luZ2ZhY2VfYXBpX2tleV9oZXJl
  
  # 券商 API 金鑰
  BROKER_API_KEY: YnJva2VyX2FwaV9rZXlfaGVyZQ==
  BROKER_SECRET_KEY: YnJva2VyX3NlY3JldF9rZXlfaGVyZQ==
  
  # 通知服務金鑰
  LINE_NOTIFY_TOKEN: bGluZV9ub3RpZnlfdG9rZW5faGVyZQ==
  TELEGRAM_BOT_TOKEN: dGVsZWdyYW1fYm90X3Rva2VuX2hlcmU=
  
  # 電子郵件設定
  SMTP_USERNAME: c210cF91c2VybmFtZV9oZXJl
  SMTP_PASSWORD: c210cF9wYXNzd29yZF9oZXJl

---
apiVersion: v1
kind: Secret
metadata:
  name: ai-trading-tls
  namespace: ai-trading
  labels:
    app: ai-trading-system
    component: tls
type: kubernetes.io/tls
data:
  # TLS 憑證和私鑰 (需要實際的憑證檔案)
  # 使用以下命令生成：
  # kubectl create secret tls ai-trading-tls --cert=path/to/tls.crt --key=path/to/tls.key -n ai-trading --dry-run=client -o yaml
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t...
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t...
